// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
)

// Injectors from inject.go:

func initBar(ctx context.Context) (Bar, error) {
	foo := ProvideFoo()
	bar := ProvideBar(foo)
	return bar, nil
}
